using ChunkL;
using ChunkL.Syntax;
using GBX.NET.Generators.Analysis;
using GBX.NET.Generators.Parsing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;

namespace GBX.NET.Generators.Generation;

internal static class EngineWriter
{
    private static readonly DiagnosticDescriptor GenerationError = new(
        "GBXNETGEN200", "Cannot generate engine source", "Cannot generate {0}: {1}",
        "GBX.NET.Generators", DiagnosticSeverity.Error, true);

    public static void Generate(SourceProductionContext context, GenerationPlan plan)
    {
        foreach (var diagnostic in plan.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic);
        }

        foreach (var layout in plan.Layouts.Values.OrderBy(static x => x.File.TypeKey, StringComparer.Ordinal))
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            try
            {
                context.AddSource($"Engines/{layout.File.Engine}/{layout.Name}.g.cs", Write(layout, plan.Layouts, plan.Existing));
            }
            catch (Exception exception) when (exception is not OperationCanceledException)
            {
                context.ReportDiagnostic(Diagnostic(layout.File, exception));
            }
        }
    }

    internal static Diagnostic Diagnostic(ParsedChunkLFile file, Exception exception) =>
        Microsoft.CodeAnalysis.Diagnostic.Create(GenerationError,
            Location.Create(file.Path, default, default), file.Syntax.Header.ClassName, exception.Message);

    public static string Write(LayoutModel layout, IReadOnlyDictionary<string, LayoutModel> layouts,
        ImmutableDictionary<string, ExistingType> existingTypes)
    {
        RequirePartial(layout.Existing);

        var code = new CodeWriter();
        code.Line("// <auto-generated />");
        code.Line("#nullable enable");
        code.BlankLine();
        
        foreach (var ns in new[] { "System", "System.IO", "System.Collections.Generic", "TmEssentials", "GBX.NET.Attributes", "GBX.NET.Serialization", "GBX.NET.Serialization.Chunking" }
            .Concat(layouts.Values.Select(static x => x.File.Namespace))
            .Distinct()
            .OrderBy(static x => x, StringComparer.Ordinal))
        {
            code.Line("using global::" + ns + ";");
        }
        code.BlankLine();
        code.Line($"namespace {layout.File.Namespace};");
        code.BlankLine();

        Documentation(code, layout.File.Syntax.Header.TrailingComment?.Text);

        if (!SyntaxOverlap.HasAttribute(layout.Existing, "Class"))
        {
            code.Line($"[Class(0x{layout.Id:X8})]");
        }

        var bases = new List<string>();
        if (layout.BaseName is not null) bases.Add(layout.BaseName);
        bases.Add("IClass");
        if (layout.SelfArchive is not null) bases.AddRange(ArchiveInterfaces(layout, layout.Scope));
        if (layout.Scope.HasVersion) bases.Add("IVersionable");

        var media = IsMedia(layout, layouts);
        if (media && layout.Scope.Fields.Any(static x => x.Name == "Keys"))
        {
            bases.Add("CGameCtnMediaBlock.IHasKeys");
        }
        
        if (media && layout.Scope.Fields.Any(static x => x.Name == "Start")
            && layout.Scope.Fields.Any(static x => x.Name == "End"))
        {
            bases.Add("CGameCtnMediaBlock.IHasTwoKeys");
        }

        code.Open("public " + (layout.IsAbstract ? "abstract " : "") + "partial class " + layout.Name + (bases.Count == 0 ? "" : " : " + string.Join(", ", bases.Distinct())));
        
        if (!SyntaxOverlap.Has(layout.Existing, "Id"))
        {
            code.Line("[Hexadecimal]");
            code.Line($"public static {(layout.BaseName is null ? "" : "new ")}uint Id => 0x{layout.Id:X8};");
        }

        code.BlankLine();
        Properties(code, layout, layout.Scope, false);

        if (layout.Name != "CMwNod" && !SyntaxOverlap.Method(layout.Existing, "DeepCloneFields", "CMwNod", "DeepCloneContext"))
        {
            code.BlankLine();
            code.Open("internal override void DeepCloneFields(CMwNod clone, DeepCloneContext context)");
            code.Line("base.DeepCloneFields(clone, context);");
            CloneFields(code, layout.Name, layout.Scope, false);
            code.Close();
        }

        foreach (var property in layout.File.Syntax.Properties)
        {
            if (SyntaxOverlap.Has(layout.Existing, property.Name)) continue;

            code.BlankLine();
            Documentation(code, property.TrailingComment?.Text);

            code.Open("public " + WireTypes.CSharp(property.Type) + (property.Type.IsNullable && property.Type.ArrayDimensions == 0 ? "?" : "") + " " + SyntaxOverlap.Escape(property.Name));
            
            var writer = new SerializationWriter(code, layout, layout.Scope, layouts, SerializationMode.ReadWrite, false);
            
            foreach (var accessor in property.Accessors)
            {
                if (accessor is GetterAccessor getter) code.Line("get => " + writer.Expression(getter.Expression) + ";");
                else if (accessor is SetterAccessor setter) { code.Open("set"); writer.Write(setter.Body); code.Close(); }
            }

            code.Close();
        }

        if (layout.Existing?.Constructors.Any(static x => !x.Modifiers.Any(SyntaxKind.StaticKeyword) && x.ParameterList.Parameters.Count == 0) != true &&
            layout.Existing?.PrimaryConstructors.Any() != true)
        {
            code.BlankLine();
            code.Open("public " + layout.Name + "()");

            if (layout.File.Syntax.Constructor is { } constructor)
                new SerializationWriter(code, layout, layout.Scope, layouts, SerializationMode.ReadWrite, false).Write(constructor.Body);
            
            code.Close();
        }

        if (media && bases.Contains("CGameCtnMediaBlock.IHasKeys") && !SyntaxOverlap.Has(layout.Existing, "IHasKeys.Keys"))
        {
            code.BlankLine();
            code.Line("IEnumerable<IKey> CGameCtnMediaBlock.IHasKeys.Keys => Keys ?? []; ");
        }
        
        if (media && bases.Contains("CGameCtnMediaBlock.IHasTwoKeys"))
        {
            foreach (var name in new[] { "Start", "End" })
                if (!SyntaxOverlap.Has(layout.Existing, "IHasTwoKeys." + name))
                {
                    code.BlankLine();
                    code.Open($"TimeSingle CGameCtnMediaBlock.IHasTwoKeys.{name}");
                    code.Line($"get => {name}{(layout.Scope.Fields.First(x => x.Name == name).Declaration.Type.IsNullable ? ".GetValueOrDefault()" : "")};");
                    code.Line($"set => {name} = value;");
                    code.Close();
                }
        }

        if (layout.SelfArchive is not null)
        {
            code.BlankLine();
            ArchiveMethods(code, layout, layout.Scope, layouts,
                layout.BaseName is not null && layouts.TryGetValue(layout.BaseName, out var parent) && parent.SelfArchive is not null ? "override " : "virtual ");
        }
        
        foreach (var chunk in layout.Chunks.OrderBy(static x => x.IsHeader ? 0 : 1).ThenBy(static x => x.Id))
        {
            Chunk(code, layout, chunk, layouts);
        }

        foreach (var archive in layout.Archives)
        {
            code.BlankLine();
            RequirePartial(archive.Value.Existing);

            var inherited = LayoutModel.Attribute(archive.Value.Attributes, "inherits");
            var archiveBases = ArchiveInterfaces(layout, archive.Value).ToList();
            var inheritedArchive = inherited is not null && layout.Archives.ContainsKey(inherited);

            if (!string.IsNullOrEmpty(inherited)) archiveBases.Insert(0, inherited!);
            if (!inheritedArchive) archiveBases.Add("IDeepCloneable");

            code.Open($"public partial class {archive.Key} : {string.Join(", ", archiveBases)}");

            Properties(code, layout, archive.Value, false);

            if (!inheritedArchive && archive.Value.Existing?.Methods.Any(static x => x.Identifier.ValueText == "DeepClone") != true)
            {
                code.BlankLine();
                code.Open("object IDeepCloneable.DeepClone(DeepCloneContext context)");
                code.Line($"var clone = ({archive.Key})MemberwiseClone();");
                code.Line("context.Register(this, clone);");
                code.Line("DeepCloneArchiveFields(clone, context);");
                code.Line("return clone;");
                code.Close();
            }

            code.BlankLine();
            code.Open($"internal {(inheritedArchive ? "override" : archive.Value.Existing?.Declarations.Any(static x => x.Modifiers.Any(SyntaxKind.SealedKeyword)) == true ? "" : "virtual")} void DeepCloneArchiveFields(object clone, DeepCloneContext context)");
            if (inheritedArchive) code.Line("base.DeepCloneArchiveFields(clone, context);");
            CloneFields(code, archive.Key, archive.Value, false);
            code.Close();

            code.BlankLine();
            ArchiveMethods(code, layout, archive.Value, layouts,
                inheritedArchive ? "override " : "virtual ");
            
            code.Close();
        }

        foreach (var enumeration in layout.File.Syntax.Enums)
        {
            if (SyntaxOverlap.Has(layout.Existing, enumeration.Name)) continue;

            code.BlankLine();
            Documentation(code, enumeration.TrailingComment?.Text);

            code.Open("public enum " + enumeration.Name);

            foreach (var member in enumeration.Members)
            {
                Documentation(code, member.TrailingComment?.Text);
                code.Line(SyntaxOverlap.Escape(member.Name) + (member.ExplicitValue is null ? "" : " = " + member.ExplicitValue) + ",");
            }

            code.Close();
        }

        foreach (var flags in layout.File.Syntax.Flags)
        {
            if (SyntaxOverlap.Has(layout.Existing, flags.Name)) continue;

            code.BlankLine();
            code.Line("[Flags]");
            code.Open("public enum " + flags.Name + " : ulong");

            foreach (var member in flags.Members)
            {
                code.Line(SyntaxOverlap.Escape(member.Name) + " = " +
                    (member.Bits.IsSingleBit ? $"1UL << {member.Bits.Start}" : $"((1UL << {member.Bits.End - member.Bits.Start + 1}) - 1) << {member.Bits.Start}") + ",");
            }

            code.Close();
        }

        if (layout.Chunks.Any(static x => !x.IsHeader) && !SyntaxOverlap.Method(layout.Existing, "NewChunk", "uint") && layout.BaseName is not null)
        {
            code.BlankLine();
            code.Line("internal override IChunk? NewChunk(uint chunkId) => chunkId switch");
            code.Line("{");
            code.Indent++;

            foreach (var chunk in layout.Chunks.Where(static x => !x.IsHeader).OrderBy(static x => x.Id))
            {
                code.Line($"0x{chunk.Id:X8} => new {chunk.Name}(),");
            }

            code.Line("_ => base.NewChunk(chunkId),");
            code.Indent--;
            code.Line("};");
        }

        code.Close();

        return code.ToString();
    }

    internal static void RequirePartial(ExistingType? existing)
    {
        if (existing is not null && (!existing.IsPartial || existing.Declarations.Any(static x => x is not Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax)))
            throw new InvalidOperationException("Existing type must be a partial class: " + existing.Key);
    }

    private static string[] ArchiveInterfaces(LayoutModel layout, ScopeModel scope)
    {
        var contextual = LayoutModel.Has(scope.Attributes, "contextual") ? "<" + layout.Name + ">" : "";

        if (scope.Separate || contextual.Length > 0)
            return scope.HasVersion
                ? ["IReadable" + contextual, "IWritable" + contextual, "IVersionable"]
                : ["IReadable" + contextual, "IWritable" + contextual];
        
        return scope.HasVersion
            ? ["IReadableWritable", "IReadable", "IWritable", "IVersionable"]
            : ["IReadableWritable", "IReadable", "IWritable"];
    }

    private static void Properties(CodeWriter code, LayoutModel layout, ScopeModel scope, bool chunk)
    {
        foreach (var field in scope.Fields)
        {
            if (chunk && !field.IsUnknown && !field.IsVersion) continue;
            if (!chunk && field.Occurrences.Any(static x => LayoutModel.Has(x.Attributes, "inherited"))) continue;

            var property = SyntaxOverlap.Escape(field.Name);
            var backing = chunk ? property : SyntaxOverlap.Backing(field.Name);
            var nullable = WireTypes.Nullable(field) && !field.IsVersion;
            var type = field.IsVersion ? "int" : WireTypes.CSharp(field.Declaration) + (nullable ? "?" : "");
            var defaultDeclaration = field.Occurrences.FirstOrDefault(static x => x.DefaultValue is not null);
            var initial = Default(type, defaultDeclaration);
            var partialProperty = SyntaxOverlap.PartialPropertyImplementation(scope.Existing, field.Name);
            var hasExisting = SyntaxOverlap.Has(scope.Existing, field.Name);

            if (!chunk)
                code.BlankLine();

            if (field.IsVersion)
            {
                if (!SyntaxOverlap.Has(scope.Existing, "Version"))
                    code.Line("public int Version { get; set; }" + (initial is null ? "" : " = " + initial + ";"));
                continue;
            }

            if (chunk)
            {
                if (partialProperty is not null)
                {
                    PartialProperty(code, partialProperty);
                }
                else if (!hasExisting)
                    code.Line("public " + type + " " + property + (initial is null ? "" : " = " + initial) + ";");
            }
            else if (!hasExisting || partialProperty is not null)
            {
                if (partialProperty is null)
                {
                    var existingBacking = SyntaxOverlap.MemberType(scope.Existing, backing.TrimStart('@'));
                    if (existingBacking is not null)
                    {
                        type = existingBacking;
                    }
                    else
                    {
                        code.Line("private " + type + " " + backing + (initial is null ? "" : " = " + initial) + ";");
                    }
                }

                Documentation(code, field.Declaration.TrailingComment?.Text);

                if (field.Occurrences.Any(static x => LayoutModel.Has(x.Attributes, "formatted")))
                    code.Line("[SupportsFormatting]");

                if (ReferenceEquals(scope, layout.Scope))
                {
                    foreach (var applied in layout.Chunks)
                    {
                        foreach (var range in AppliedWithChunkRanges.Get(applied, field.Name, layout.Chunks, layout.Id))
                        {
                            var arguments = range.End < int.MaxValue ? $"({range.Start}, {range.End})" :
                                range.Start > 0 ? $"({range.Start})" : "";
                            code.Line("[AppliedWithChunk<" + applied.Name + ">" + arguments + "]");
                        }
                    }
                }

                if (partialProperty is not null)
                {
                    PartialProperty(code, partialProperty);
                }
                else
                {
                    var privateSet = SyntaxOverlap.Option(scope.Existing, "PrivateSet") == "true" ? "private " : "";
                    var external = LayoutModel.Has(field.Declaration.Attributes, "external") && field.Declaration.Type.ArrayDimensions == 0;

                    code.Open($"public {type} {property}");
                    code.Line($"get => {(external ? "this." + backing + "File?.GetNode(ref this." + backing + ") ?? " : "")}this.{backing};");
                    code.Line($"{privateSet}set => this.{backing} = value;");
                    code.Close();
                }
            }

            if (LayoutModel.Has(field.Declaration.Attributes, "external") && field.Declaration.Type.ArrayDimensions == 0)
            {
                var fileField = backing.TrimStart('@') + "File";

                if (!SyntaxOverlap.Has(scope.Existing, fileField))
                {
                    code.Line((chunk ? "public " : "private ") + "Components.GbxRefTableFile? " + fileField + ";");
                }

                if (!chunk && !SyntaxOverlap.Has(scope.Existing, field.Name + "File"))
                {
                    code.BlankLine();
                    code.Open($"public Components.GbxRefTableFile? {property}File");
                    code.Line($"get => {fileField};");
                    code.Line($"set => {fileField} = value;");
                    code.Close();
                }

                if (!chunk && !SyntaxOverlap.Has(scope.Existing, "Get" + field.Name))
                {
                    code.BlankLine();
                    code.Line($"public {type} Get{field.Name}(GbxReadSettings settings = default, bool exceptions = false) => {fileField}?.GetNode(ref {backing}, settings, exceptions) ?? {backing};");
                }
            }
        }
    }

    private static void PartialProperty(CodeWriter code, PropertyDeclarationSyntax property)
    {
        var modifiers = string.Join(" ", property.Modifiers.Select(static x => x.Text));
        var accessors = string.Join(" ", property.AccessorList!.Accessors.Select(static x =>
            (x.Modifiers.Count == 0 ? "" : string.Join(" ", x.Modifiers.Select(static y => y.Text)) + " ") + x.Keyword.Text + ";"));

        code.Line($"{modifiers} {property.Type} {property.Identifier.Text} {{ {accessors} }}");
    }

    private static string? Default(string type, FieldDeclaration? field)
    {
        if (field?.DefaultValue is null) return null;

        var value = ChunkLParser.WriteExpression(field.DefaultValue).Replace("::", ".");
        if (value != "empty") return value;

        type = type.TrimEnd('?');

        if (type.StartsWith("List<", StringComparison.Ordinal)) return "new()";
        if (type.EndsWith("[]", StringComparison.Ordinal)) return "[]";
        if (type == "string") return "string.Empty";

        return type + ".Empty";
    }

    private static void Chunk(CodeWriter code, LayoutModel layout, ChunkModel chunk, IReadOnlyDictionary<string, LayoutModel> layouts)
    {
        RequirePartial(chunk.Scope.Existing);
        code.BlankLine();
        Documentation(code, chunk.Declaration.TrailingComment?.Text);

        if (!SyntaxOverlap.HasAttribute(chunk.Scope.Existing, "Chunk"))
        {
            code.Line($"[Chunk(0x{chunk.Id:X8}{(chunk.Declaration.TrailingComment is { } comment ? ", " + SymbolDisplay.FormatLiteral(comment.Text, true) : "")})]");
        }

        if (chunk.Declaration.VersionQualifiers.Count > 0 && !SyntaxOverlap.HasAttribute(chunk.Scope.Existing, "ChunkGameVersion"))
        {
            var qualifiers = chunk.Declaration.VersionQualifiers;
            code.Line("[ChunkGameVersion(" + string.Join(" | ", qualifiers.Select(static x => "GameVersion." + x.Label)) +
                (qualifiers.Any(static x => x.MaxVersion.HasValue) ? ", " + string.Join(", ", qualifiers.Select(static x => x.MaxVersion ?? -1)) : "") + ")]");
        }

        var baseId = LayoutModel.Attribute(chunk.Declaration.Attributes, "base");
        var baseType = baseId is not null ? "Chunk" + (LayoutModel.Hex(baseId) <= 0xFFF ? LayoutModel.Hex(baseId) | layout.Id : LayoutModel.Hex(baseId)).ToString("X8") :
            (chunk.IsHeader ? "HeaderChunk" : LayoutModel.Has(chunk.Declaration.Attributes, "skippable") ? "SkippableChunk" : "Chunk") + "<" + layout.Name + ">";
        
        var interfaces = chunk.Scope.HasVersion ? ", IVersionable" : "";

        var selfContained = LayoutModel.Has(chunk.Declaration.Attributes, "self-contained");
        if (selfContained)
        {
            interfaces += ", ISelfContainedChunk<" + layout.Name + ">";
        }

        code.Open("public partial class " + chunk.Name + " : " + baseType + interfaces);

        if (!SyntaxOverlap.Has(chunk.Scope.Existing, "Id"))
        {
            code.Line($"public override uint Id => 0x{chunk.Id:X8};");
        }

        if (LayoutModel.Has(chunk.Declaration.Attributes, "ignore") && !SyntaxOverlap.Has(chunk.Scope.Existing, "Ignore"))
        {
            code.Line("public override bool Ignore => true;");
        }

        if (selfContained)
        {
            if (!SyntaxOverlap.Has(chunk.Scope.Existing, "Node"))
            {
                code.Line("public " + layout.Name + " Node { get; set; } = new();");
            }

            if (!SyntaxOverlap.Has(chunk.Scope.Existing, "ISelfContainedChunk.Node"))
            {
                code.Line("IClass ISelfContainedChunk.Node { get => Node; set => Node = (" + layout.Name + ")value; }");
            }
        }

        if (chunk.Declaration.VersionQualifiers.Count > 0 && !SyntaxOverlap.Has(chunk.Scope.Existing, "GameVersion"))
        {
            code.Line("public override GameVersion GameVersion => " + string.Join(" | ", chunk.Declaration.VersionQualifiers.Select(static x => "GameVersion." + x.Label)) + ";");
        }

        var demonstration = LayoutModel.Has(chunk.Declaration.Attributes, "demonstration");
        var omitMembers = LayoutModel.OmitsDemonstrationMembers(chunk.Declaration.Attributes);

        if (!omitMembers)
            Properties(code, layout, chunk.Scope, true);

        if (!omitMembers && !SyntaxOverlap.Method(chunk.Scope.Existing, "DeepCloneFields", "Chunk", "DeepCloneContext"))
        {
            code.BlankLine();
            code.Open("internal override void DeepCloneFields(Chunk clone, DeepCloneContext context)");
            code.Line("base.DeepCloneFields(clone, context);");
            CloneFields(code, chunk.Name, chunk.Scope, true);
            code.Close();
        }
        
        if (!demonstration && chunk.Declaration.Body.Count > 0)
        {
            foreach (var mode in chunk.Scope.Separate ? new[] { SerializationMode.Read, SerializationMode.Write } : new[] { SerializationMode.ReadWrite })
            {
                var ioType = mode switch
                {
                    SerializationMode.Read => "GbxReader",
                    SerializationMode.Write => "GbxWriter",
                    _ => "GbxReaderWriter"
                };

                var io = mode switch
                {
                    SerializationMode.Read => "r",
                    SerializationMode.Write => "w",
                    _ => "rw"
                };

                if (SyntaxOverlap.Method(chunk.Scope.Existing, mode.ToString(), layout.Name, ioType))
                {
                    continue;
                }

                code.BlankLine();
                code.Open($"public override void {mode}({layout.Name} n, {ioType} {io})");

                new SerializationWriter(code, layout, chunk.Scope, layouts, mode, true).Write(chunk.Declaration.Body);

                code.Close();
            }
        }

        code.Close();
    }

    private static void CloneFields(CodeWriter code, string className, ScopeModel scope, bool chunk)
    {
        var copied = new HashSet<string>(StringComparer.Ordinal);

        foreach (var field in scope.Fields)
        {
            if (!chunk && field.Occurrences.Any(static x => LayoutModel.Has(x.Attributes, "inherited"))) continue;
            if (!chunk && SyntaxOverlap.Has(scope.Existing, field.Name)) continue;
            if (chunk && !field.IsUnknown && !field.IsVersion) continue;

            var name = field.IsVersion ? "Version" : chunk ? field.Name : SyntaxOverlap.Backing(field.Name);
            if (!copied.Add(name)) continue;

            var type = field.IsVersion ? "int" : WireTypes.CSharp(field.Declaration);
            code.Line($"(({className})clone).{SyntaxOverlap.Escape(name)} = {CloneExpression(type, "this." + SyntaxOverlap.Escape(name))};");
        }

        if (scope.Existing is null) return;

        foreach (var field in scope.Existing.Fields)
        {
            if (field.Modifiers.Any(SyntaxKind.StaticKeyword) ||
                field.Modifiers.Any(SyntaxKind.ConstKeyword) ||
                field.Modifiers.Any(SyntaxKind.ReadOnlyKeyword)) continue;

            foreach (var variable in field.Declaration.Variables)
            {
                var name = variable.Identifier.ValueText;
                if (!copied.Add(name)) continue;

                var escaped = SyntaxOverlap.Escape(name);
                code.Line($"(({className})clone).{escaped} = {CloneExpression(field.Declaration.Type.ToString(), "this." + escaped)};");
            }
        }

        foreach (var property in scope.Existing.Properties)
        {
            if (property.ExplicitInterfaceSpecifier is not null ||
                property.Modifiers.Any(SyntaxKind.StaticKeyword) ||
                property.AccessorList?.Accessors.Any(x => x.IsKind(SyntaxKind.SetAccessorDeclaration)) != true ||
                property.AccessorList.Accessors.Any(x => x.Body is not null || x.ExpressionBody is not null)) continue;

            var name = property.Identifier.ValueText;
            if (!copied.Add(name)) continue;

            var escaped = SyntaxOverlap.Escape(name);
            code.Line($"(({className})clone).{escaped} = {CloneExpression(property.Type.ToString(), "this." + escaped)};");
        }
    }

    private static string CloneExpression(string type, string value)
    {
        var name = type.TrimEnd('?').Split('<')[0].Split('.').Last();

        if (type.TrimEnd('?').EndsWith("[]", StringComparison.Ordinal)) return $"context.CloneArray({value})!";
        if (name is "List" or "IList" or "IReadOnlyList" or "ICollection" or "IReadOnlyCollection" or "IEnumerable")
            return $"context.CloneList({value})!";
        if (name is "Dictionary" or "IDictionary" or "IReadOnlyDictionary")
            return $"context.CloneDictionary({value})!";
        if (name is "HashSet" or "ISet") return $"context.CloneHashSet({value})!";

        return $"context.Clone({value})!";
    }

    private static void ArchiveMethods(CodeWriter code, LayoutModel layout, ScopeModel scope, IReadOnlyDictionary<string, LayoutModel> layouts, string modifier)
    {
        if (scope.Existing?.Declarations.Any(static x => x.Modifiers.Any(SyntaxKind.SealedKeyword)) == true)
        {
            modifier = "";
        }

        var contextual = LayoutModel.Has(scope.Attributes, "contextual");
        
        foreach (var mode in scope.Separate || contextual ? new[] { SerializationMode.Read, SerializationMode.Write } : new[] { SerializationMode.ReadWrite })
        {
            var ioType = mode switch
            {
                SerializationMode.Read => "GbxReader",
                SerializationMode.Write => "GbxWriter",
                _ => "GbxReaderWriter"
            };

            var io = mode switch
            {
                SerializationMode.Read => "r",
                SerializationMode.Write => "w",
                _ => "rw"
            };

            var parameterTypes = contextual ? new[] { ioType, layout.Name, "int" } : new[] { ioType, "int" };
            
            if (SyntaxOverlap.Method(scope.Existing, mode.ToString(), parameterTypes))
            {
                continue;
            }

            code.BlankLine();
            code.Open($"public {modifier}void {mode}({ioType} {io}, {(contextual ? layout.Name + " n, " : "")}int v = 0)");
            
            new SerializationWriter(code, layout, scope, layouts, mode, false).Write(scope.Body);
            
            code.Close();
        }

        // Separate chunk methods also need to call archives implemented with a single
        // ReadWrite method. Adapt those interfaces without duplicating serialization.
        if (!scope.Separate && !contextual)
        {
            foreach (var mode in new[] { SerializationMode.Read, SerializationMode.Write })
            {
                var ioType = mode == SerializationMode.Read ? "GbxReader" : "GbxWriter";
                var io = mode == SerializationMode.Read ? "r" : "w";

                if (SyntaxOverlap.Method(scope.Existing, mode.ToString(), ioType, "int"))
                {
                    continue;
                }

                code.BlankLine();
                code.Open($"public {modifier}void {mode}({ioType} {io}, int v = 0)");
                code.Line($"using var rw = new GbxReaderWriter({io});");
                code.Line("ReadWrite(rw, v);");
                code.Close();
            }
        }
    }

    private static bool IsMedia(LayoutModel layout, IReadOnlyDictionary<string, LayoutModel> layouts)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);

        while (layout.BaseName is not null && seen.Add(layout.Name))
        {
            if (layout.BaseName == "CGameCtnMediaBlock")
            {
                return true;
            }
                
            if (!layouts.TryGetValue(layout.BaseName, out layout!))
            {
                return false;
            }
        }

        return false;
    }

    private static void Documentation(CodeWriter code, string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return;
        }

        code.Line("/// <summary>");

        foreach (var line in text!.Split('\n'))
        {
            code.Line("/// " + line.Trim().Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;"));
        }

        code.Line("/// </summary>");
    }
}
