using GBX.NET.Generators.Analysis;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;

namespace GBX.NET.Generators.Generation;

internal static class ManagerWriter
{
    public static void Generate(SourceProductionContext context, IReadOnlyDictionary<string, LayoutModel> layouts,
        ImmutableArray<KeyValuePair<string, string>> resources)
    {
        var classes = layouts.Values.OrderBy(static x => x.Id).ToArray();

        var code = new CodeWriter();
        code.Line("// <auto-generated />");
        code.Line("#nullable enable");
        code.BlankLine();
        code.Line("using global::System;");
        code.Line("using global::System.Collections.Generic;");
        code.Line("using GBX.NET.Components;");
        code.Line("using GBX.NET.Serialization.Chunking;");
        code.Line("using GBX.NET.Engines.MwFoundations;");
        code.BlankLine();
        code.Line("namespace GBX.NET.Managers;");
        code.BlankLine();

        code.Open("public static partial class ClassManager");
        code.Line("internal static Dictionary<Type, uint> ClassIds { get; } = new()");
        code.Line("{");
        code.Indent++;
        
        foreach (var layout in classes)
        {
            code.Line($"[typeof({layout.QualifiedName})] = 0x{layout.Id:X8},");
        }

        code.Indent--;
        code.Line("};");
        code.BlankLine();

        Switch(code, "public static partial Type? GetType(uint classId)", "classId", classes.Select(x => ($"0x{x.Id:X8}", $"typeof({x.QualifiedName})")), "null");
        Switch(code, "internal static partial IClass? New(uint classId)", "classId", classes.Where(static x => !x.IsAbstract).Select(x => ($"0x{x.Id:X8}", $"new {x.QualifiedName}()")), "null");
        Switch(code, "internal static partial GbxHeader? NewHeader(GbxHeaderBasic basic, uint classId)", "classId", classes.Select(x => ($"0x{x.Id:X8}", $"new GbxHeader<{x.QualifiedName}>(basic)")), "null");
        Switch(code, "internal static partial Gbx? NewGbx(GbxHeader header, GbxBody body, IClass node)", "header.ClassId", classes.Select(x => ($"0x{x.Id:X8}", $"new Gbx<{x.QualifiedName}>((GbxHeader<{x.QualifiedName}>)header, body, ({x.QualifiedName})node)")), "null");
        
        foreach (var header in new[] { true, false })
        {
            var seen = new HashSet<uint>();
            var chunks = classes.SelectMany(x => x.Chunks.OrderBy(static c => c.Id)
                .Where(c => c.IsHeader == header && seen.Add(c.Id))
                .Select(c => ($"0x{c.Id:X8}", $"new {x.QualifiedName}.{c.Name}()")));
            Switch(code, "internal static partial " + (header ? "IHeaderChunk? NewHeaderChunk" : "IChunk? NewChunk") + "(uint chunkId)", "chunkId", chunks, "null");
        }

        Switch(code, "internal static partial bool IsChunkIdRemapped(uint chunkId)", "chunkId", classes.SelectMany(static x => x.Chunks).Where(static x => LayoutModel.Has(x.Declaration.Attributes, "not-remapped")).GroupBy(static x => x.Id).Select(x => ($"0x{x.Key:X8}", "false")), "true");
        Switch(code, "internal static partial uint? GetBaseClassId(uint classId)", "classId", classes.Where(x => x.BaseName is not null && layouts.ContainsKey(x.BaseName)).Select(x => ($"0x{x.Id:X8}", $"0x{layouts[x.BaseName!].Id:X8}")), "null");

        var names = new Dictionary<uint, string>();
        foreach (var resource in resources.Where(static x => x.Key is "ClassId.txt" or "ClassIdManual.txt"))
        {
            foreach (var pair in Rows(resource.Value))
            {
                if (uint.TryParse(pair.Key.Replace("0x", ""), System.Globalization.NumberStyles.HexNumber, null, out var id))
                {
                    names[id] = pair.Value;
                }
            }
        }

        foreach (var layout in classes)
        {
            names[layout.Id] = layout.Name;
        }
        
        code.Line("#if DEBUG");
        code.Line("public static partial string? GetName(uint classId, bool all)");
        code.Line("#else");
        code.Line("public static partial string? GetName(uint classId) => GetName(classId, true);");
        code.Line("public static partial string? GetName(uint classId, bool all)");
        code.Line("#endif");
        code.Open("");
        code.Line("if (!all && !ClassIds.ContainsValue(classId)) return null;");
        code.Line("return classId switch");
        code.Line("{");
        code.Indent++;

        foreach (var name in names.OrderBy(static x => x.Key))
        {
            code.Line($"0x{name.Key:X8} => {Literal(name.Value)},");
        }

        code.Line("_ => null,");
        code.Indent--;
        code.Line("};");
        code.Close();
        code.BlankLine();
        code.Line("#if !DEBUG");
        code.Line("public static partial uint? GetId(string className) => GetId(className, true);");
        code.Line("#endif");
        code.BlankLine();
        code.Open("public static partial uint? GetId(string className, bool all)");
        code.Line("uint? id = className switch");
        code.Line("{");
        code.Indent++;

        foreach (var name in names.GroupBy(static x => x.Value).OrderBy(static x => x.Key, StringComparer.Ordinal))
        {
            code.Line($"{Literal(name.Key)} => 0x{name.First().Key:X8},");
        }

        code.Line("_ => null,");
        code.Indent--;
        code.Line("};");
        code.Line("return all || (id.HasValue && ClassIds.ContainsValue(id.Value)) ? id : null;");
        code.Close();

        foreach (var kind in new[] { "Wrap", "Unwrap" })
        {
            var rows = Rows(resources.FirstOrDefault(x => x.Key == kind + ".txt").Value ?? "");

            code.BlankLine();
            code.Open("internal static partial uint " + kind + "(uint classId)");
            code.Line("var chunkPart = classId & 0xFFF;");
            code.Line("var classPart = classId & 0xFFFFF000;");
            code.Line("return (classPart switch");
            code.Line("{");
            code.Indent++;

            foreach (var row in rows) 
            {
                code.Line("0x" + row.Key + " => 0x" + row.Value + ",");
            }

            code.Line("_ => classPart,");
            code.Indent--;
            code.Line("}) | chunkPart;");
            code.Close();
        }

        var extensions = Rows(resources.FirstOrDefault(static x => x.Key == "Extensions.txt").Value ?? "");
        
        Switch(code, "public static partial IEnumerable<string> GetFileExtensions(uint classId)", "classId",
            extensions.Select(x => ("0x" + x.Key, "new string[] { " + string.Join(", ", x.Value.Split([' ', '\t'], StringSplitOptions.RemoveEmptyEntries).Skip(1).Select(Literal)) + " }")), "Array.Empty<string>()");
        
        code.Close();

        context.AddSource("Managers/ClassManager.g.cs", code.ToString());

        var collections = Rows(resources.FirstOrDefault(static x => x.Key == "CollectionId.txt").Value ?? "").ToArray();
        var collection = new CodeWriter();

        collection.Line("// <auto-generated />");
        collection.Line("#nullable enable");
        collection.BlankLine();
        collection.Line("using global::System.Collections.Generic;");
        collection.Line("using global::System.Collections.Immutable;");
        collection.BlankLine();
        collection.Line("namespace GBX.NET.Managers;");
        collection.BlankLine();
        collection.Open("public static partial class CollectionManager");
        collection.Line("public static ImmutableDictionary<int, string> Collections { get; } = new Dictionary<int, string>()");
        collection.Line("{");
        collection.Indent++;

        foreach (var pair in collections)
        {
            collection.Line($"[{pair.Key}] = {Literal(pair.Value)},");
        }

        collection.Indent--;
        collection.Line("}.ToImmutableDictionary();");
        collection.BlankLine();

        Switch(collection, "public static partial string? GetName(int id)", "id", collections.Select(x => (x.Key, Literal(x.Value))),
            "CustomCollections.TryGetValue(id, out var name) ? name : null");

        collection.Close(); 
        
        context.AddSource("Managers/CollectionManager.g.cs", collection.ToString());
    }

    private static void Switch(CodeWriter code, string signature, string value, IEnumerable<(string Key, string Value)> cases, string fallback)
    {
        code.BlankLine();
        code.Line(signature + " => " + value + " switch");
        code.Line("{");
        code.Indent++;

        foreach (var (key, caseValue) in cases)
        {
            code.Line(key + " => " + caseValue + ",");
        }

        code.Line("_ => " + fallback + ",");
        code.Indent--;
        code.Line("};");
    }

    private static string Literal(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, true);
    
    private static IEnumerable<KeyValuePair<string, string>> Rows(string source)
    {
        foreach (var line in source.Split('\n'))
        {
            var text = line.Split(["//"], StringSplitOptions.None)[0].Trim();
            var separator = text.IndexOfAny([' ', '\t']);
            if (separator > 0)
            {
                yield return new KeyValuePair<string, string>(text.Substring(0, separator), text.Substring(separator).Trim());
            }
        }
    }
}
