//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBX.NET {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GBX.NET.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 00
        ///  105 CMwCmdExpStringConcat
        ///01 MwFoundations
        ///  001 CMwNod
        ///  003 CMwEngine
        ///  005 CMwCmd
        ///  006 CMwParam
        ///  007 CMwParamClass
        ///  008 CMwParamStruct
        ///  009 CMwParamAction
        ///  00C CMwParamBool
        ///  00D CMwParamEnum
        ///  00E CMwParamInteger
        ///  00F CMwParamIntegerRange
        ///  010 CMwParamNatural
        ///  011 CMwParamNaturalRange
        ///  012 CMwCmdFastCall
        ///  013 CMwParamReal
        ///  014 CMwParamRealRange
        ///  015 CMwParamString
        ///  016 CMwParamVec3
        ///  017 CMwParamIso3
        ///  018 CMwParamColor
        ///  019 CMwParamVec2
        ///  01A CMwParamIso4
        ///  0 [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string ClassID {
            get {
                return ResourceManager.GetString("ClassID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 0301A000 -&gt; 2E001000
        ///0301C000 -&gt; 2E002000
        ///03031000 -&gt; 090F4000
        ///0313B000 -&gt; 2E009000
        ///
        ///0900D000 -&gt; 0900F000
        ///09063000 -&gt; 09026000
        ///
        ///21080000 -&gt; 24003000
        ///2108D000 -&gt; 2403F000
        ///21089000 -&gt; 2404A000
        ///
        ///24003000 -&gt; 03043000
        ///24004000 -&gt; 03033000
        ///24005000 -&gt; 0304E000
        ///24006000 -&gt; 03036000
        ///24007000 -&gt; 03057000
        ///24008000 -&gt; 03058000
        ///24009000 -&gt; 030D4000
        ///2400A000 -&gt; 0301A000
        ///2400B000 -&gt; 03044000
        ///2400C000 -&gt; 0305B000
        ///2400D000 -&gt; 0301F000
        ///2400E000 -&gt; 0301D000
        ///2400F000 -&gt; 0301E000
        ///24011000 -&gt; 0305A000
        /// [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string ClassIDMappings {
            get {
                return ResourceManager.GetString("ClassIDMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 0 Desert Speed
        ///1 Snow Alpine
        ///2 Rally
        ///3 Island
        ///4 Bay
        ///5 Coast
        ///6 Stadium
        ///7 Basic
        ///8 Plain
        ///9 Moon
        ///10 Toy
        ///11 Valley
        ///12 Canyon
        ///13 Lagoon
        ///14 Deprecated_Arena
        ///17 TMCommon
        ///18 Canyon4
        ///19 Canyon256
        ///20 Valley4
        ///21 Valley256
        ///22 Lagoon4
        ///23 Lagoon256
        ///24 Stadium4
        ///25 Stadium256
        ///26 Stadium
        ///100 History
        ///101 Society
        ///102 Galaxy
        ///200 Gothic
        ///201 Paris
        ///202 Storm
        ///203 Cryo
        ///204 Meteor
        ///205 Meteor4
        ///206 Meteor256
        ///299 SMCommon
        ///10000 Vehicles
        ///10001 Orbital
        ///10002 Actors
        ///10003 Common
        ///-1 Unassigned.
        /// </summary>
        internal static string CollectionID {
            get {
                return ResourceManager.GetString("CollectionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný .
        /// </summary>
        internal static string FreeBlock {
            get {
                return ResourceManager.GetString("FreeBlock", resourceCulture);
            }
        }
    }
}
