name: CI

on:
  push:
    branches: [ "master", "dev" ]
    paths: [ ".github/workflows/ci.yml", "Src/**", "Benchmarks/**", "Generators/**", "Resources/**", "Samples/**", "Tests/**", "Tools/**", "GBX.NET.slnx" ]
  pull_request:
    branches: [ "master", "dev" ]
    paths: [ ".github/workflows/ci.yml", "Src/**", "Src/**", "Benchmarks/**", "Generators/**", "Resources/**", "Samples/**", "Tests/**", "Tools/**", "GBX.NET.slnx" ]
  workflow_dispatch:

jobs:
  ci:
    name: Continuous Integration
    uses: bigbang1112/workflows/.github/workflows/ci.yml@main
    with:
      dotnet-version: |
        10.0.x
        9.0.x
        8.0.x
      workloads: wasm-tools